name: HACS Validation

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hacs:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.private }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration